### ISSUE TITLE
Goutte Factory sending through wrong Guzzle config

### ISSUE THREAD

**Issue by catharsisjelly** [Behat/MinkExtension#230] opened 2015-12-18 11:30 UTC
Hi there,

We have been using Mink for a while with our self cert SSL and after an upgrade via composer it's not not been working. Were currently running the following

* Mink 1.7.0
* Behat 3.0.15
* Mink Extension 2.1.0
* Mink Goutte Driver 1.2.0
* Guzzle 6

I found that I needed to change the configuration to my behat to be the following

```
default:
    extensions:
        Behat\Symfony2Extension: ~
        Behat\MinkExtension:
            sessions:
                default:
                    goutte:
                        guzzle_parameters:
                            verify: false
```

So in theory everything should be fine but our self-cert is still being checked reguardless of what we tell Mink. After some digging we found that the parameter is not being passed through to Guzzle, the problem lies in `GoutteFactory` line 93 where it does

```php
return new Definition('GuzzleHttp\Client', array(array('defaults' => $parameters)));
```

The parameter being passed to Guzzle are being put one level deeper than they need to be. Now I find it hard to believe that the problem lies with this bit of code but it is the only real explanation. I have written a little bit of test code to try and prove it using Guzzle direct. The following fails

```php
$url = 'https://my.url.com';
$client = new GuzzleHttp\Client(['defaults' => ['verify' => false]]);
$var = $client->request('GET', $url);
```

Whereas this passes

```php
$url = 'https://my.url.com';
$client = new GuzzleHttp\Client(['verify' => false]);
$var = $client->request('GET', $url);
```

If I remove the extra layer in `GoutteFactory` e.g. 

```php
return new Definition('GuzzleHttp\Client', array($parameters));
``` 

Our SSL is skipped as expected. I'm still digging in the problem a bit but as the Mink driver and Guzzle are so widely used it feels very odd that I have to change `GoutteFactory` for this to work. Sorry for the wall of text but any help is appreciated

**Comment by epfremmer** [comment] 2015-12-22 21:27
I ran into the same issue when setting up a new project using the goutte driver and library. It looks like Goutte v3 uses Guzzle 6 which changed the client config format. I worked around it in the meantime by adding Goutte v2 to my composer dependencies which uses Guzzle 5 and the old config format.

I believe this should work as a possible solution without breaking BC, but want to make sure that it looks acceptable for a pull request. Let me know what you think.

https://github.com/Behat/MinkExtension/compare/master...epfremmer:master

**Comment by catharsisjelly** [comment] 2015-12-23 09:17
Good to know I'm not the only one and going mad :)

**Comment by Haehnchen** [comment] 2016-01-11 11:39
@epfremmer same issue here. guzzle6 changed arguments. i can confirm your changes are working. for now downgrading `goutte` is working. maybe open a merge request so @stof can extend the last commit in `GoutteFactory`

```
"fabpot/goutte": "~2.0"

  - Removing guzzlehttp/guzzle (6.1.1)
  - Installing guzzlehttp/guzzle (5.3.0)
    Downloading: 100%
    Extracting archive

  - Removing fabpot/goutte (v3.1.2)
  - Installing fabpot/goutte (v2.0.4)
    Downloading: 100%
    Extracting archive
```

**Comment by Evoke-PHP** [comment] 2016-01-11 22:28
@epfremmer I confirm the fix worked for me too.  It is almost exactly as I would have written it.  I would make one change.  Reflection is not needed as the constant from the interface is publicly available.  So, the isGuzzle6 becomes:

    private function isGuzzle6()
    {
        return interface_exists('GuzzleHttp\ClientInterface') &&
            version_compare(\GuzzleHttp\ClientInterface::VERSION, '6.0.0', '>=');
    }

**Comment by idmontie** [comment] 2016-01-13 15:52
:+1: I ended up rolling back to ``"behat/mink-goutte-driver": "1.1",` in order to get guzzle to use my verify parameter.

**Comment by Haehnchen** [comment] 2016-02-17 10:32
fixed by https://github.com/Behat/MinkExtension/commit/7f0c691d24784b1ef924fb58ff0cfef709ca38de. but not implements a version check

**Comment by stof** [comment] 2016-02-17 10:38
@Haehnchen the issue is that your fix broke support for Guzzle 4 and 5 (and so for Goutte 2). Only Guzzle 6 does not need the ``default`` key

**Closed** 2016-02-26 12:15 UTC
