### ISSUE TITLE
Only works on first scenario

### ISSUE THREAD

**Issue by jazerix** [Behat/MinkExtension#196] opened 2015-02-26 22:24 UTC
I'm currently trying to run behat on windows. I'm running into a problem where only the first scenario works, even though the next one is identical to the first one. 

I'm dumping the response headers when printing the current url, and it's totally different. 

    /**
     * Prints current URL to console.
     *
     * @Then /^print current URL$/
     */
    public function printCurrentUrl()
    {
        $sess = $this->getSession();
        var_dump($sess->getStatusCode(), $sess->getResponseHeaders());
        echo $this->getSession()->getCurrentUrl();
    }

![enter image description here](http://i60.tinypic.com/1551kw8.png)

The output is also completely different. 

First result gives me this:
![enter image description here](http://i61.tinypic.com/s3zdr4.png)

The the second one (which is identical to the previous one).
![enter image description here](http://i62.tinypic.com/262sfb6.png)

I'm using MinkContext with Laravel

**Comment by aik099** [comment] 2015-02-27 07:58
No same problem on Linux? Does it work when you swap 2 scenarios?

**Comment by jazerix** [comment] 2015-02-27 08:26
It doesn't. However I found it to be working when I removed the base_url from my behat.yml file. Even though that doesn't make sense (to me at least), as it prints out the same url :-/

**Comment by stof** [comment] 2015-02-27 08:56
@jazerix which Mink driver are you using ?

**Comment by jazerix** [comment] 2015-02-27 12:17
I'm unsure. This is my behat.yml file :) 

    default:
        extensions:
            Laracasts\Behat: ~
            Behat\MinkExtension:
                default_session: laravel
                laravel: ~
                show_cmd: %s

**Comment by stof** [comment] 2015-02-27 13:42
Can you give me the link to this Laracasts extension ? It is probably the one giving a ``laravel`` driver type for MinkExtension

**Comment by jazerix** [comment] 2015-02-27 16:22
Certainly :) This is the repo https://github.com/laracasts/Behat-Laravel-Extension

**Comment by stof** [comment] 2015-02-28 10:23
the issue is the way they are implementing their Mink driver: https://github.com/laracasts/Behat-Laravel-Extension/blob/205a3d217d33d4315d20d0f3497edd65a8b5443e/src/Driver/KernelDriver.php#L23 Here, they are calling the constructor again but without the second argument. this is why subsequent scenarios are broken.

**Comment by jazerix** [comment] 2015-02-28 11:49
In that case I'm sorry for the inconvenience. I've opened an issue there :) thanks for the help ^^

**Comment by stof** [comment] 2015-03-02 10:44
Closing this issue because it is not in MinkExtension itself and the discussion should continue on laracasts

**Closed by stof** 2015-03-02 10:44 UTC
